### ISSUE TITLE
When connecting to a V9.0 instance getting panic: http: invalid pattern

### ISSUE THREAD

**Issue by mikekuzak** [ibm-messaging/mq-metric-samples#214]
Hi, 

When trying to connect to a V9.0 Instance I'm getting the following error: 

```
IBM MQ metrics exporter for Prometheus monitoring
Build         : 20230427-112348
Commit Level  : 3ff7e4e
Build Platform: Linux/GenuineIntel

time="2023-04-27T11:35:15Z" level=info msg="Trying to connect as client with external configuration"
time="2023-04-27T11:35:16Z" level=info msg="Connected to queue manager QM_MCM_DEV"
time="2023-04-27T11:35:27Z" level=info msg="IBMMQ Describe started"
time="2023-04-27T11:35:27Z" level=info msg="Platform is UNIX"
panic: http: invalid pattern

goroutine 8 [running]:
net/http.(*ServeMux).Handle(0xf1c420, {0x0, 0x0}, {0x9a26e0, 0xc0002b0d80})
        /usr/lib/go-1.17/src/net/http/server.go:2434 +0x24c
net/http.Handle(...)
        /usr/lib/go-1.17/src/net/http/server.go:2483
main.startServer()
        /go/src/github.com/ibm-messaging/mq-metric-samples/cmd/mq_prometheus/main.go:205 +0xab
created by main.main
        /go/src/github.com/ibm-messaging/mq-metric-samples/cmd/mq_prometheus/main.go:73 +0x138
```

Tried both approaches: 

```
 environment:
      - MQSERVER=MCM.CH.ENT/TCP/us2-uwbsr7.mydomain.com(1414)
```
or 

```
    connName: us2-uwbsr7(1414)
    channel: MCM.CH.ENT
```

Also tried to use a lower version of the MQ client libs: 9.2.0.0
Same issue. 

Thanks for any advise.

**Comment by ibmmqmet** [comment]
You've not shown the rest of your configuration. This usually means the `prometheus.metricsPath` hasn't been set. If you've run the build scripts, then the complete config file is a concatenation of the _config.common.yaml_ and the collector-specific piece. And that would set the value. Also see #50

**Comment by mikekuzak** [comment]
@ibmmqmet 
Hi Mark, yes you were right, the mq_prometheus.yaml was incomplete. I used the latest code now and I'm able to connect to our v9.0 instance and get metrics. 
Thank you
