### ISSUE TITLE
./mq_prometheus.sh does not honour queues="!SYSTEM.*"

### ISSUE THREAD

**Issue by kidharb** [ibm-messaging/mq-metric-samples#29]
Please include the following information in your ticket.

- mq-metrics-samples version(s) that are affected by this issue.
- A small code sample or description that demonstrates the issue.

I can connect to my remote Queue manager successfully as I get the below debug.

> INFO[0000] IBMMQ Describe started
> INFO[0000] Platform is ZOS
> INFO[0000] Listening on port 9157

My ```mq_prometheus.sh``` is as below.

```
#!/bin/bash

# This is used to start the IBM MQ monitoring service for Prometheus

# The queue manager name comes in from the service definition as the
# only command line parameter
qMgr=$1

# Set the environment to ensure we pick up libmqm.so etc
# Try to run it for a local qmgr; if that fails fallback to a
# default
# If this is a client connection, then deal with no known qmgr of the given name.
. /opt/mqm/bin/setmqenv -m $qMgr -k >/dev/null 2>&1
if [ $? -ne 0 ]
then
  . /opt/mqm/bin/setmqenv -s -k
fi

# A list of queues to be monitored is given here.
# It is a set of names or patterns ('*' only at the end, to match how MQ works),
# separated by commas. When no queues match a pattern, it is reported but
# is not fatal.
# The set can also include negative patterns such as "!SYSTEM.*".
queues="!SYSTEM.*"

# An alternative is to have a file containing the patterns, and named
# via the ibmmq.monitoredQueuesFile option.

# Do similar for channels
channels="*"

# See config.go for all recognised flags
ARGS="-ibmmq.queueManager=$qMgr"
ARGS="$ARGS -ibmmq.monitoredQueues=$queues"
ARGS="$ARGS -ibmmq.monitoredChannels=$channels"
ARGS="$ARGS -ibmmq.monitoredTopics=#"
ARGS="$ARGS -ibmmq.monitoredSubscriptions=*"
ARGS="$ARGS -rediscoverInterval=1h"
ARGS="$ARGS -ibmmq.useStatus=true"
ARGS="$ARGS -ibmmq.client=true"
ARGS="$ARGS -ibmmq.userid=<username>"
ARGS="$ARGS -ibmmq.password=<password"
ARGS="$ARGS -log.level=info"

# This may help with some issues if the program has a SEGV. It
# allows Go to do a better stack trace.
export MQS_NO_SYNC_SIGNAL_HANDLING=true


# Start via "exec" so the pid remains the same. The queue manager can
# then check the existence of the service and use the MQ_SERVER_PID value
# to kill it on shutdown.
exec ./mq_prometheus $ARGS

```
However, I get the following exception when I navigate to <ip_address>:9157/metrics in a browser
```
goroutine 25 [running]:
runtime/debug.Stack(0x2920c, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/ibmmq.ReadPCFParameter(0xc000436024, 0xffdc, 0xffdc, 0xc0003b5
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golan8
github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric.inquireObjects(0x8fb2c9, 0x1, 0x1, 0x1, 0x0, 0xc0003e
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golan+0xab0
github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric.discoverQueues(0x7fff23527528, 0x1d, 0x24, 0x0)
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golan+0x97
github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric.discoverAndSubscribe(0x7fff23527528, 0x1d, 0xc0002436, 0x8fc968)
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golan+0x1f0
github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric.RediscoverAndSubscribe(0x7fff23527528, 0x1d, 0x902a01
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golan+0xe7
main.(*exporter).Collect(0xc00010a300, 0xc0001a4060)
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/cmd/mq_prometheus/exporter.go:243 +0x497
github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_gola34 +0x19d
created by github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_gola45 +0x57d
panic: label topic: value "SYSTEM.BROKER.ADMIN.STREAM/MQ/\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x4\xa0:O\xb4\xa4:O\xb4\xa8:O\xb4\xb4:O\xb4\xb0" is not valid UTF-8

goroutine 25 [running]:
github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_golang/prometheus.(*GaugeVec).With(0xc00006c138, 0xc0003935c0, 0x8fb
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_gola+0xc2
main.(*exporter).Collect(0xc00010a300, 0xc0001a4060)
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/cmd/mq_prometheus/exporter.go:374 +0x2a5
github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_gola34 +0x19d
created by github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/corp.dsarena.com/abkb298-admin/Projects/Proj1/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_gola45 +0x57d
```

It seems that the offending line is 

```
panic: label topic: value "SYSTEM.BROKER.ADMIN.STREAM/MQ/\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x4\xa0:O\xb4\xa4:O\xb4\xa8:O\xb4\xb4:O\xb4\xb0" is not valid UTF-8
```

I would like to know why the exporter is still parsing messages from ```SYSTEM.BROKER.ADMIN.STREAM``` even though I have excluded in my mq_prometheus.sh by adding ```queues="!SYSTEM.*"``` to it 
Or if that is not the offending line, what could be the possible causes for the stack dump?
I have compiled v4.13 (latest) of the code.

**Comment by kidharb** [comment]
It turns out that there are no topics on the queue so setting 
```
ARGS="$ARGS -ibmmq.monitoredTopics=*"
```
did the trick.
